### ISSUE TITLE
Wrong response code when InterceptorFlowController.invokeRequestHandlers throws an error

### ISSUE THREAD

**Issue by predic8** [membrane/service-proxy#186]
See: https://groups.google.com/forum/#!topic/membrane-monitor/0o6nJqeuOig

**Comment by rrayst** [comment]
See discussion in the google group: Throwing IOException closes the TCP connection. Throwing anything else returns 500. This is working as designed.

The problem is some (yet unidentified) component throwing a JsonParseException indirectly extending IOException. 

The JsonParseException should be wrapped in a non-IOException before throwing it.

But as the component is unidentified, I'm closing this bug.
