### ISSUE TITLE
Feature: smart node selection (load-balancing/failover) by monitoring failures

### ISSUE THREAD

**Issue by fabiankessler** [membrane/service-proxy#211]
The README of this GitHub project currently lists these 4 bullets under "What is Membrane":

*    a Service Virtualization layer,
*    an API Gateway,
*    a synchronous ESB for HTTP based Integration,
*    a Security Proxy.

The 2 most important features for me are not listed: load-balancing and failover.
As of now the built-in functionality is pretty basic. 

This feature request is for smarter handling. I'm going to contribute a DispatchingStrategy that monitors service failures and acts accordingly to them.

**Comment by fabiankessler** [comment]
See https://github.com/fabiankessler/service-proxy/commit/74321c571bd23a557818c8d42904ee7eb9795553

**Comment by fabiankessler** [comment]
I had to start over with my clone in order to make separated pull requests per topic. So ignore the commit message from above. A clean pull request will come as soon as the other pending requests from me are resolved.

**Comment by predic8** [comment]
@xorpherion have you fixed that already?

**Comment by rrayst** [comment]
This issue is well on the way. Things to do:
* If a node returns status code 4XX, count this as "OK".
* If a node returns 5XX, increment a per-node counter. Only take the node down, if the per-node counter reaches a configurable limit (defaulting to, say, 10).
* If a node returns <500, set the counter to 0.

* After a configurable amount of time (and -1 to disable this) after taking a node down, take any node back up. (maybe try to connect to it, before taking it fully up).

**Comment by xorpherion** [comment]
i will have a look at this

**Comment by xorpherion** [comment]
Nodes should now be taken down based on the description of @rrayst . The "take nodes back up" part is coming next.

**Comment by fabiankessler** [comment]
Did you look at my DispatchingStrategy? The branch is at https://github.com/fabiankessler/service-proxy/tree/FaultMonitoringStrategy-branch3 the code is here https://github.com/fabiankessler/service-proxy/tree/FaultMonitoringStrategy-branch3/core/src/main/java/com/predic8/membrane/core/interceptor/balancer/faultmonitoring especially the FaultMonitoringStrategy

A pull request was here https://github.com/membrane/service-proxy/pull/217
