### ISSUE TITLE
Memory issue when body size is large

### ISSUE THREAD

**Issue by olegnetanya** [membrane/service-proxy#310]
Hi,

We are using version 4.5.1 and encounter out of memory issue when body size is larger than available memory of application (uploading big files).

Class: Body
Method: writeNotRead

All chunks are saved in memory in the method:
`chunks.add(new Chunk(chunk));`

When size of body is larger than application memory, following exception is thrown:
java.lang.OutOfMemoryError: Java heap space

Thanks,
Oleg

**Comment by xorpherion** [comment]
Hi @olegnetanya,
you are right, that Membrane is saving all exchanges in memory. This is "usually" because only exchanges small in size are routed through Membrane and as an admin you possibly want to have access to the routed exchanges (e.g. through the Admin UI of Membrane). 

You can disable this behaviour (saving of all exchanges in memory) by activating the "streaming" mode. This is currently done by excluding the exchange store (and all other exchange body listeners) from the transport and configuring the http client (of the transport) to retries=1. If you need help with that please write again here and i will make a sample configuration.

**Comment by olegnetanya** [comment]
Hi @xorpherion ,

I will appreciate if you provide configuration for activating the "streaming" mode.

Thanks,
Oleg

**Comment by xorpherion** [comment]
Hi @olegnetanya ,
sorry for the late response. I was busy the last week.

I just made a small example that shows you how to enable streaming.

`<router>

        <transport>
            <ruleMatching />
            <dispatching />
            <reverseProxying />
            <userFeature />
            <httpClient>
                <httpClientConfig maxRetries="1"/>
            </httpClient>
        </transport>

        <serviceProxy port="2255">
            <webServer docBase="C:\\Users\\Predic8\\Downloads\\" generateIndex="true"/>
        </serviceProxy>        
    </router>`

The most important takeaway here is that i have excluded the exchange store from the transport (would normally come after rule matching) and that i have set the httpClient to only send the content one time to one destination.
The exchange store has to be excluded as it caches all messages. The httpClient can only sent streamed content one time as it would not be available anymore on a second attempt.

Details:
For streaming to work you can not have BodyObservers on your exchanges. The exchange store uses BodyObservers and thus you have to disable it. Also some other parts of Membrane use BodyObservers, but those are also labeled as NonRelevantBodyObserver. When Membrane finds none or only NonRelevantBodyObservers it does not cache the content anymore = streaming. This does also mean that you lose some functionality. If you can you should route your large files through a single service proxy which you then put into a separate router without exchange store. 

Hope i could help. If you do not need any help anymore i will close this issue.

**Comment by olegnetanya** [comment]
Hi @xorpherion ,

This information is very helpful.
You can close the issue.

Thanks,
Oleg.

**Comment by xorpherion** [comment]
Great!
May you do well!
