### ISSUE TITLE
Enhancement Enable relative path for OpenID Provider

### ISSUE THREAD

**Issue by precoder** [membrane/service-proxy#358]
Hello,
We have made a few derivations on our copy from the upstream.
We want to share them with you so if you find them useful you can also benefit from the code changes.

This is the 2nd of 4 changes.

Motivation:
Enable Membrane to start on a relative path,
so it can be chained under another reverse proxy such as Ngnix.

**Comment by DJGummikuh** [comment]
A little bit on detail for this one as well:
We're running membrane as reverse-proxy, SSL Terminator, webserver and OIDC Provider.
Since our software contains a web client we wanted to provide that one under /, while restrictive network policies of customers as well as CORS considerations prompted us towards making the OIDC provider accessible under the same port as everything else. 

This change request allows you to put the login into OIDC anywhere (while not removing the ability to place it under /).
This allows us to have the following endpoint structure:
/ - web client
/api - Backend endpoints
/auth - Login service (login mask, callback, well-known config etc.)
